### ISSUE TITLE
Solution(?) for error while installing pyreason-gym

### ISSUE THREAD

**Issue by kmukherji** [lab-v2/pyreason-gym#1]
Error displayed:

> error: Multiple top-level packages discovered in a flat-layout: ['media', 'pyreason_gym']

Solution that worked for me:
`+    py_modules=[],`
in setup.py line 6.

Verify if installation is correct when this is used.

**Comment by dyumanaditya** [comment]
Great, thanks @kmukherji I'll check this out. Can you open a PR and reference this issue?
