### ISSUE TITLE
[Core] Error while getting the raw RGB rendering of the grid

### ISSUE THREAD

**Issue by devrz45** [lab-v2/pyreason-gym#6]

**Comment by devrz45** [comment]
https://github.com/lab-v2/pyreason-gym/blob/c6c670902bc0e0f58dfa25af5a777d10497b92f4/tests/observation_rgb/test.py#L15

**Comment by devrz45** [comment]
I took a pull from main branch and that resolved the not implemented error but I am getting another error: `GridWorldEnv._render_frame()` missing 1 required positional argument: 'observation'`
Please take a look at https://github.com/lab-v2/pyreason-gym/blob/6773788f2f49594f582003283abc1a28bb853ee9/pyreason_gym/envs/grid_world.py#L114 observation is never passed to the render method.

**Comment by dyumanaditya** [comment]
Solved as of #11
